In [1]:
import os
import io
import random
import numpy as np
import pandas as pd
import networkx as nx
from PIL import Image
import autokeras as ak
import tensorflow as tf
from numpy import asarray
from tensorflow import keras
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from tensorflow.keras.callbacks import CSVLogger
from sklearn.datasets import load_files
from sklearn.metrics import classification_report
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold

# Generate the images array

In [2]:
images = []
labels = []
import os
rootdir = 'gcImages'
for subdir, dirs, files in os.walk(rootdir):
    for file in files:        
        instance = os.path.join(subdir, file)
        if instance.endswith('.jpg'):
            #im = Image.open(instance)
            im = Image.open(instance).convert('L')
            pix = im.load()
            width, height = im.size
            pixel_values = list(im.getdata())
            data = asarray(im)
            print(data)
            images.append(data)
            #labels.append(int(subdir.split("/")[-1][-1])                        
images2 = np.asarray(images)
images2 = images2.reshape((images2.shape[0], 32, 32))
print(images2.shape)

[[ 0  0 14 ...  0  0  0]
 [ 0 16 40 ...  0  0  0]
 [ 9 38 69 ...  1  1  1]
 ...
 [ 0  0  0 ...  0  0  6]
 [ 0  0  0 ...  1  9 15]
 [ 0  0  1 ...  9 18 19]]
[[ 4  0 21 ...  1  2  1]
 [ 0  0 23 ...  2  0  0]
 [18 32 57 ...  3  0  0]
 ...
 [ 0  1  2 ... 72 38  2]
 [ 0  0  0 ... 40 15  0]
 [ 1  0  0 ...  5  0  6]]
[[ 0  0 28 ...  0  3 15]
 [ 0 15 55 ...  1  0  0]
 [23 44 76 ... 16  0  0]
 ...
 [ 0  5 17 ... 92 64 62]
 [ 2  1  0 ... 66  0  0]
 [11  1  0 ... 63  0  0]]
[[ 0  0 42 ...  0  0  1]
 [ 0  5 49 ...  0  1  3]
 [38 48 72 ...  3  0  0]
 ...
 [ 0  0  2 ...  0  3  0]
 [ 3  2  0 ...  0  8  7]
 [ 1  0  0 ...  0 17 21]]
[[ 4  0  3 ...  2  0  1]
 [ 2  2 12 ...  0  0  0]
 [ 0 19 39 ... 25 31 39]
 ...
 [ 0  6 28 ...  0  0  0]
 [ 1  0 32 ...  0  0  0]
 [ 2  0 30 ...  0  0  1]]
[[ 8  0 11 ...  5  4  0]
 [ 0  5 32 ...  0  0  4]
 [ 7 36 63 ... 48 41 46]
 ...
 [ 4  0 48 ...  0  3  3]
 [ 0  5 35 ...  6  0  0]
 [ 0 17 41 ...  2  0 10]]
[[ 7  0 40 ...  1  5  4]
 [ 0  5 58 ...  1  1  0]
 [35 53 88 ...

[[176 247 255 ... 255 255 255]
 [248 193 248 ... 254 253 252]
 [255 249 190 ... 255 255 255]
 ...
 [253 255 255 ... 187 247 255]
 [253 255 255 ... 247 190 247]
 [254 255 255 ... 255 247 182]]
[[108  34  80 ...  54  23   8]
 [ 40  17  50 ...  24   0  15]
 [ 80  64  42 ...  62  71   0]
 ...
 [ 47  34  60 ...  98  37  40]
 [ 20   0  84 ...  35  28  31]
 [ 13   0   4 ...  52  10   7]]
[[83 68 78 ... 49 25 15]
 [77  0  4 ... 38 15 23]
 [68 19 28 ... 26 12 45]
 ...
 [55 38 26 ...  8 13 32]
 [29 10 16 ... 18 40 47]
 [ 9 25 55 ... 36 54 24]]
[[ 90  83  77 ...   6  13  34]
 [ 95  38  26 ...  15 105  22]
 [ 80  18  51 ...   1   2   0]
 ...
 [  0  25   0 ...  20  42  13]
 [ 19 102   0 ...  54  24  24]
 [ 38  12   3 ...   0  38  41]]
[[ 8  0  9 ...  9 12 20]
 [ 0  0 31 ...  2  3 11]
 [ 8 32 61 ...  0  0  7]
 ...
 [ 9  5  0 ...  0  0  0]
 [15  7  0 ...  0  0  0]
 [19 10  1 ...  0  0  0]]
[[  7   0  88 ...   1   1   1]
 [  0   5  97 ...   0   0   0]
 [ 93  99 123 ...   1   1   1]
 ...
 [  0   1   1 

[[92 57 44 ... 31 15 41]
 [42  9 10 ... 22  7 46]
 [60 22 41 ... 19 11 46]
 ...
 [27 17 11 ...  0 47 29]
 [20 12 11 ... 47 27  4]
 [40 46 39 ... 35 12 92]]
[[120  75  73 ...  37  13  14]
 [ 68   0  27 ...  55  22  19]
 [ 84  19   0 ... 103  33  16]
 ...
 [ 38  54  90 ...  22  39  12]
 [ 10  32  37 ...  45  33  17]
 [ 13  25   0 ...  18   2  14]]
[[117  88 117 ...  27  98  23]
 [ 89   0  30 ... 121  30  27]
 [110  37  75 ...  96  51  51]
 ...
 [ 46 120  95 ...  86  70  45]
 [ 84  32  55 ...  85  70  63]
 [ 25  29  54 ...  41  59  75]]
[[107 100 121 ...  61  46  88]
 [103  20  59 ...  42  44  38]
 [129  63  29 ...  74  56  87]
 ...
 [ 56  48  69 ...  71 116  44]
 [ 39  50  57 ... 117  69  73]
 [ 91  42  83 ...  46  67 171]]
[[ 77 109  43 ...   3   0   0]
 [104  22   8 ...  13   7   2]
 [ 52  12  36 ...   7   1   0]
 ...
 [  3   6  12 ...   0   0   7]
 [  2   0   9 ...   5   2   0]
 [  0   0   5 ...   6   1   0]]
[[92 36  0 ...  0  0  3]
 [32  6 65 ...  3  0  0]
 [ 0 66 46 ...  7  0  0]
 

[[119  19   0 ...   2   8  15]
 [ 26  51  25 ...   1   3   7]
 [  0  27  80 ...   2   1   1]
 ...
 [  2   1   2 ...  16   8   8]
 [ 10   5   2 ...   9   0   0]
 [ 17   8   1 ...  14   2   5]]
[[94  4  0 ...  3  0  0]
 [11 37 36 ...  0  0  0]
 [ 0 27 65 ...  0  0  6]
 ...
 [ 0  0  0 ... 23 14  0]
 [ 0  0  0 ... 13 12  0]
 [ 1  4  3 ...  0  0  0]]
[[161 135  75 ...  37  93  80]
 [134   9  30 ...  61  59  67]
 [ 82  17  48 ...  62  70  29]
 ...
 [ 49  44  60 ...  76   7  45]
 [ 82  74  60 ...  29  46  50]
 [ 82  66  34 ...  40  59  57]]
[[107  98 181 ...  74  43  65]
 [100  51 148 ... 115  79  96]
 [174 160  67 ...  51  88  76]
 ...
 [ 76 113  67 ...   0 113 112]
 [ 45  79  97 ... 140 117 124]
 [ 64  95  71 ...  95 126  80]]
[[ 77 125 129 ...  92  51  41]
 [127  64  98 ...  71  92  37]
 [129  95  63 ...  67  84 113]
 ...
 [ 81  74  59 ...  82 145 105]
 [ 65  95  83 ... 152  99  75]
 [ 38  28 116 ... 109  74 101]]
[[ 84 118 134 ... 105 127  94]
 [105 134 101 ... 124  55 109]
 [138  92  65 

[[145 182 213 ... 141  99 147]
 [173 210 150 ... 186 214 175]
 [207 152 133 ... 196 193 160]
 ...
 [130 193 186 ... 150 150 180]
 [107 216 196 ... 147 177 158]
 [143 173 156 ... 186 158 140]]
[[197 186 178 ... 161 164 139]
 [190 184 175 ... 188 181 245]
 [184 185 180 ... 194 159 217]
 ...
 [173 190 195 ... 112 186 214]
 [168 183 159 ... 182 161 168]
 [132 242 217 ... 216 160 127]]
[[198 221 224 ... 155 169 182]
 [228 168 212 ... 186 157 217]
 [221 207 150 ... 225 214 201]
 ...
 [171 156 234 ... 140 157 180]
 [172 151 215 ... 158 162 188]
 [178 233 186 ... 178 192 100]]
[[195 253 226 ... 171 216 183]
 [255 209 242 ... 201 246 225]
 [227 239 179 ... 226 242 230]
 ...
 [171 189 230 ... 198 230 247]
 [225 229 251 ... 237 155 227]
 [182 225 244 ... 241 234 168]]
[[200 245 255 ... 252 222 203]
 [235 192 223 ... 237 250 255]
 [255 228 200 ... 230 247 247]
 ...
 [255 250 231 ... 212 203 249]
 [226 253 247 ... 222 216 242]
 [204 241 255 ... 239 232 209]]
[[165 231 252 ... 250 226 191]
 [233 195

[[  0   3 114 ...  10  11   7]
 [  0  47 116 ...   0   1   7]
 [118 123 125 ...   0   0   5]
 ...
 [ 10   3   0 ...   0   0   0]
 [ 13   0   0 ...   0   0   0]
 [ 11   0   7 ...   0   0   0]]
[[  5  14 166 ...   3  10  14]
 [ 15  61 164 ...   0   0   4]
 [169 171 103 ...   5   0   0]
 ...
 [  0   5   0 ...   0  10   3]
 [  7   0   0 ...   9  22   0]
 [ 19   0   0 ...   9   0   0]]
[[  0  29 178 ...   7   0   0]
 [ 21  53 141 ...   0   7   2]
 [177 152  82 ...   0   3   0]
 ...
 [  9   3   0 ...   0   0   0]
 [  0   4   0 ...   0   0   0]
 [  0   3   3 ...   0   0   0]]
[[  0   0 161 ...   8   0   0]
 [  6  25 145 ...   0   4   5]
 [149 145 126 ...   5  13   0]
 ...
 [  4  11   0 ...   1   0   0]
 [  0   2   9 ...   0   0   1]
 [  4   0  15 ...   0   1   2]]
[[  0   5 110 ...   3   5   0]
 [  2  35 108 ...   0   0   0]
 [109 105 124 ...   0   3   3]
 ...
 [  7   0   0 ...  11   0   5]
 [  7   0   0 ...   4   0   2]
 [  0   4   9 ...   0   1   0]]
[[  0  14 178 ...   7   0   0]
 [ 21  46

[[  7  25 209 ...   3   6   0]
 [ 22  89 144 ...   0  24  58]
 [207 152  48 ...   0 145 219]
 ...
 [  6   0   1 ... 118 152 192]
 [ 11  23 147 ... 169  67  53]
 [  0  52 217 ... 201  47   0]]
[[  0  44 215 ... 216  66   0]
 [ 32  51 159 ... 151  29  12]
 [224 150  28 ...  14   0   4]
 ...
 [216 161  15 ...  48 188 235]
 [ 66  33   0 ... 184 105  51]
 [  0  13   6 ... 246  37   0]]
[[  2  46 215 ...   0   8   0]
 [ 33  51 157 ...  45  55  67]
 [223 149  25 ... 179 198 230]
 ...
 [  0  41 187 ...  51 176 245]
 [  0  48 200 ... 179  97  37]
 [  0  77 238 ... 245  44   0]]
[[  0  36 215 ...   3   1  13]
 [ 31  80 152 ...  24   0   5]
 [221 155  48 ... 138  29   0]
 ...
 [  0  36 136 ...   0   5  12]
 [  0   0  29 ...  14   0   0]
 [ 17   4   0 ...   6   0  26]]
[[  0  35 214 ...   9   0   6]
 [ 28  74 160 ...  46  53  43]
 [225 153  33 ... 192 189 195]
 ...
 [ 13  56 196 ...  63 148 211]
 [  0  45 190 ... 146  60  43]
 [  9  45 193 ... 208  56   0]]
[[152 183 222 ... 197 199 172]
 [191 178

[[196 242 241 ... 199 215 198]
 [243 197 232 ... 206 231 238]
 [251 232 182 ... 228 245 211]
 ...
 [196 198 230 ... 189 243 231]
 [209 240 255 ... 232 185 241]
 [200 240 203 ... 238 243 193]]
[[208 254 250 ... 255 255 255]
 [254 204 255 ... 255 255 255]
 [250 255 205 ... 255 255 255]
 ...
 [255 255 255 ... 206 255 249]
 [255 255 255 ... 255 202 251]
 [255 255 255 ... 249 251 203]]
[[56 47 63 ...  3 37 43]
 [51 12 10 ... 32 46 23]
 [62 25 41 ... 17 30 14]
 ...
 [ 9 37 28 ... 15 24 42]
 [33 31 15 ... 30 71 73]
 [43 35 12 ... 44 65 54]]
[[100  50  46 ...  29   6  30]
 [ 44   1  31 ...  39  44  43]
 [ 49  10  65 ...  22  29  26]
 ...
 [ 16  46  23 ...   6  17  65]
 [  9  48  17 ...  21  31  57]
 [ 33  34  39 ...  57  55   3]]
[[86 37 98 ... 21 14 32]
 [49 10 51 ... 17 16 39]
 [86 47 42 ... 32 27 45]
 ...
 [ 9 17 41 ... 39 42 22]
 [19 22 29 ... 30 41 23]
 [32 35 40 ... 31 18 30]]
[[ 84  82 101 ...  26  62  22]
 [ 81  48  38 ...  59  37  47]
 [ 99  47  33 ...   0  14  35]
 ...
 [ 28  39  17 

[[189 193 220 ... 154 132 124]
 [185 175 184 ... 169 202 157]
 [233 191 164 ... 187 185 166]
 ...
 [153 179 180 ... 157 172 186]
 [125 205 179 ... 171 145 173]
 [123 159 171 ... 184 171 143]]
[[196 188 204 ... 145 175 180]
 [198 118 169 ... 190 183 185]
 [202 169 178 ... 205 178 171]
 ...
 [151 188 202 ... 195 204 186]
 [177 179 178 ... 201 113 200]
 [180 185 175 ... 191 193 151]]
[[194 202 201 ... 189 170 158]
 [198 159 200 ... 194 202 172]
 [206 212 143 ... 186 206 180]
 ...
 [186 202 183 ... 149 201 233]
 [160 209 200 ... 205 161 207]
 [159 180 178 ... 230 209 112]]
[[206 216 181 ... 144 190 168]
 [223 162 193 ... 194 202 186]
 [178 201 169 ... 210 207 192]
 ...
 [153 191 207 ... 176 210 224]
 [180 189 208 ... 200 171 192]
 [180 186 185 ... 225 190 142]]
[[194 225 211 ... 163 199 172]
 [219 171 236 ... 219 208 195]
 [211 250 165 ... 201 184 214]
 ...
 [172 226 201 ... 156 223 213]
 [202 197 174 ... 225 195 207]
 [168 204 218 ... 210 208 190]]
[[195 217 222 ... 183 183 219]
 [207 198

[[135 131 160 ...  73  88  76]
 [128  75  76 ... 100 112 119]
 [152  94  67 ...  93  66 121]
 ...
 [ 78  95 106 ... 132 121  94]
 [ 86 103  65 ... 118 151 109]
 [ 74 124 126 ...  89 118 103]]
[[128 171 140 ...  98  88  83]
 [169 108  96 ...  85 109 130]
 [137  86 110 ...  91  95 133]
 ...
 [ 86  89  93 ... 100  75 104]
 [ 85 112 104 ...  92  82 112]
 [ 79 143 120 ...  91 113 123]]
[[118 163 154 ... 132 147 104]
 [161 141 123 ... 121 124 117]
 [161 124 101 ... 147 124  98]
 ...
 [136 116 151 ...  87 112 117]
 [141 115 123 ... 115  91 127]
 [103 127  97 ... 108 143  93]]
[[81 13  8 ... 21 21  8]
 [30 37 50 ... 11 14  3]
 [ 8 43 14 ... 12 18 11]
 ...
 [17 12 12 ...  0  0  5]
 [23 20 23 ...  1 22 26]
 [ 2  4 12 ...  6 21  5]]
[[130 184 140 ... 129 138 110]
 [181  80 106 ... 148 150 150]
 [147 108  65 ... 143 177 147]
 ...
 [130 149 143 ... 122 128 104]
 [132 159 178 ... 123 104 148]
 [112 144 154 ...  92 154 110]]
[[130 179 178 ... 115 143 104]
 [177 102 154 ... 131 143 148]
 [184 149  75 

[[  2 139 255 ...  11   3   1]
 [145  93 133 ... 124 117 148]
 [255 142  25 ... 255 255 235]
 ...
 [  0 136 255 ... 114  80  94]
 [  8 127 252 ...  88   0   2]
 [  0 136 255 ...  86   0  12]]
[[  4 145 250 ...   0   5   0]
 [148  71 141 ... 129 146 128]
 [250 159  11 ... 253 242 255]
 ...
 [  0 138 255 ...  19 148 248]
 [  0 143 246 ... 153  88 132]
 [  1 124 255 ... 253 128   5]]
[[  0 139 247 ...   0   8   5]
 [140 139 110 ...  81 155 126]
 [255  92   0 ... 193 255 255]
 ...
 [  0  90 194 ...  48  80 217]
 [ 11 152 254 ...  79 139 181]
 [  3 125 254 ... 231 169   3]]
[[  5 139 251 ...   2   0   0]
 [146  79 141 ... 149 142 149]
 [255 137  24 ... 254 250 250]
 ...
 [  7 146 251 ...   8 160 244]
 [  0 135 254 ... 166  78 146]
 [  9 143 247 ... 247 149   0]]
[[  2 139 255 ...  58   0   6]
 [145  93 133 ... 168 123 115]
 [255 142  25 ... 255 240 255]
 ...
 [ 56 166 247 ...  81 118 225]
 [  0 140 250 ... 107  99 182]
 [ 10 109 255 ... 220 187   0]]
[[  6 147 249 ... 255 123   0]
 [143  83

[[  4 231 255 ...   0  10   0]
 [226  57   0 ... 228 229 230]
 [255   0   1 ... 255 255 255]
 ...
 [  4 231 255 ...   5 231 255]
 [  0 226 255 ... 212  32 238]
 [  5 233 255 ... 255 235   2]]
[[  0 247 254 ...   0  13   0]
 [252   4 245 ... 218 232 235]
 [255 241   3 ... 255 248 245]
 ...
 [  0 218 255 ...  22 234 246]
 [  1 233 255 ... 225   4 244]
 [  0 236 246 ... 255 239   2]]
[[  0 233 255 ... 229   0   0]
 [237  23 238 ... 254 239 239]
 [255 236   5 ... 241 251 255]
 ...
 [239 250 253 ...   7 233 254]
 [  0 239 255 ... 221  32 236]
 [  0 245 244 ... 255 229   6]]
[[ 15 228 255 ... 255 224   2]
 [226  30 243 ... 249 252 241]
 [247 248   0 ... 255 255 251]
 ...
 [255 255 255 ...   5 242 255]
 [233 245 244 ... 231  20 243]
 [  0 244 255 ... 255 241   0]]
[[  0 233 255 ... 255 246 255]
 [237  23 238 ... 253 255 248]
 [255 236   5 ... 250 251 247]
 ...
 [253 255 255 ...   1 248 240]
 [251 255 255 ... 246   0 255]
 [255 236 254 ... 244 241   1]]
[[  0 237 255 ... 255 255 255]
 [236  21

[[ 59 253 195 ...  38   0  41]
 [245   0  21 ...  68  57 189]
 [203   4 154 ...   0 162   0]
 ...
 [ 43  60  11 ... 110 135 137]
 [  8  35 156 ... 138 120 137]
 [ 33 204   0 ... 120 144  95]]
[[ 44 254 248 ...   3  14   5]
 [240  44 244 ...   0 255  63]
 [246 255  89 ... 130 162   0]
 ...
 [  0   4 139 ...  65 226 246]
 [ 14 255 149 ... 243  78  78]
 [ 16  44   2 ... 241  81   0]]
[[ 33 245 253 ...   0   0   6]
 [238   0   8 ...   0   0   0]
 [255  14   0 ...  35   0   5]
 ...
 [  5   2  30 ... 118   6   1]
 [  0   0   0 ...   4   0   5]
 [  3   3   0 ...   0   2   2]]
[[ 56 220 255 ...  47  61  31]
 [221  64 213 ... 255 195 244]
 [255 231   0 ... 178  77 245]
 ...
 [ 43 255 164 ... 166 119 253]
 [ 34 200  98 ... 115 130  62]
 [ 54 228 248 ... 255  64   5]]
[[ 70 216 205 ...  52  70  61]
 [226  13   6 ... 225 141 165]
 [208   0   4 ... 175  77 111]
 ...
 [ 55 226 179 ... 136   2 204]
 [ 56 161  70 ...  14   0 230]
 [ 62 172  90 ... 200 226  59]]
[[ 49 236 236 ...   7  27  52]
 [235  83

[[ 98 223 247 ...   6  83  91]
 [228 120 187 ... 163 255 169]
 [255 183  80 ... 215 255  28]
 ...
 [  8 154 217 ... 121 154 218]
 [ 79 255 255 ... 164 122 163]
 [ 96 173  29 ... 226 155   0]]
[[ 91 232 223 ...  78  44   0]
 [243  76  67 ... 250 175  72]
 [209  57  34 ... 158 222 255]
 ...
 [ 81 251 152 ...   0 246 253]
 [ 48 180 213 ... 254   3 172]
 [  0  76 255 ... 248 180 108]]
[[ 73 255 249 ...  34  25  95]
 [255  70 242 ... 255 126 223]
 [233 251 102 ... 209 240 245]
 ...
 [ 27 255 199 ... 138 223 255]
 [ 20 125 255 ... 239  95 184]
 [ 94 232 236 ... 255 183   0]]
[[102 200 148 ...   0   5   0]
 [198   0  13 ...  41   2   2]
 [158   5   0 ...  12   3   0]
 ...
 [  9  37  21 ...   6   0   6]
 [  3   0   5 ...   1   0   0]
 [  0   1   0 ...   8   0   0]]
[[ 86 239 248 ...  88 102  86]
 [240 102 199 ... 166 102 219]
 [249 212  75 ... 208 190 236]
 ...
 [ 89 165 208 ...  56 212 250]
 [ 99  99 195 ... 204  94 248]
 [ 84 226 235 ... 244 251  81]]
[[115 175 251 ... 252 186  60]
 [175   0

[[105 255 174 ...  19 130 116]
 [252  69  38 ... 211 185 185]
 [182  27 168 ... 234  86   0]
 ...
 [ 16 205 241 ... 144 115 227]
 [144 174  89 ... 123   0 138]
 [116 176  10 ... 232 149 115]]
[[124 225 138 ...  92  46  15]
 [208  56 198 ... 155 255 156]
 [142 205 162 ... 163 255 204]
 ...
 [100 160 165 ... 184 142 246]
 [ 31 255 255 ... 144  85 153]
 [ 15 166 184 ... 244 151   0]]
[[119 252 255 ... 124  93  48]
 [244   9 198 ... 251 250 251]
 [255 220 165 ... 224 222 214]
 ...
 [112 251 229 ... 137 244 230]
 [ 94 255 226 ... 255 104 252]
 [ 57 235 213 ... 226 249 111]]
[[145 213 219 ... 145 114 109]
 [197   0 186 ... 142 255 243]
 [230 189  87 ... 210 250 194]
 ...
 [134 156 203 ...   0 218 160]
 [108 242 255 ... 224 144 161]
 [119 244 192 ... 150 169  11]]
[[120 249 250 ...  88 129 114]
 [252  25 183 ... 255 238 250]
 [255 178 121 ... 240 212 200]
 ...
 [ 96 255 243 ...  20 198 255]
 [134 240 212 ... 187 168 229]
 [116 243 206 ... 255 225 121]]
[[116 239 250 ... 255 230 115]
 [237 109

[[135 236 227 ... 137  90  46]
 [255 137 150 ... 177 193  77]
 [228 132  82 ... 166 174 151]
 ...
 [151 190 164 ... 107 253 203]
 [ 78 192 177 ... 239 144 223]
 [ 46  85 137 ... 201 217 150]]
[[123 116 118 ...   9   3   1]
 [135   0  12 ...   0   0   2]
 [110  12   0 ...   2  17  12]
 ...
 [ 14   0   1 ...   5   9  44]
 [  1   0  19 ...   7   0  23]
 [  0  11   1 ...  47  28   0]]
[[152 183 201 ... 130 104 111]
 [183 136 200 ... 251 184 254]
 [213 186 161 ... 108 128 202]
 ...
 [129 233  99 ... 184 211 138]
 [105 201 137 ... 203  85  75]
 [110 255 186 ... 136  77 138]]
[[122 127  46 ...   4   0   0]
 [131   0  10 ...   0   8  29]
 [ 48   0  18 ...   4  15  38]
 ...
 [  0   0   3 ...  10  56  19]
 [  5   0  17 ...  62   4  51]
 [  0  28  52 ...  23  51  33]]
[[134 103 139 ...   4   0   4]
 [113   5   0 ...  11  54   0]
 [121   0  11 ...  26   7  46]
 ...
 [  7  23  41 ...  82  62  13]
 [  4  46   0 ...  58   0  58]
 [  0   4  49 ...   0  74  29]]
[[106 170  14 ...   1   0   4]
 [156 129

[[158 244 211 ...  99  77 113]
 [241  93 168 ... 129 184 125]
 [217 189  49 ... 181 172 199]
 ...
 [ 91 119 187 ... 159 237 158]
 [ 76 190 183 ... 247 117 162]
 [114 123 190 ... 161 162 183]]
[[156 201 196 ... 138 139 158]
 [205  18 230 ... 173 255 255]
 [178 238 145 ... 188 235 239]
 ...
 [130 175 185 ... 166 243 255]
 [151 255 236 ... 231  86 213]
 [156 249 244 ... 255 226 150]]
[[146 200 246 ... 254 255 165]
 [200 138 214 ... 255 253 255]
 [248 208 178 ... 226 238 249]
 ...
 [246 255 223 ... 113 219 224]
 [243 255 251 ... 204 170 247]
 [177 255 247 ... 233 240 150]]
[[152 234 252 ... 170 128 122]
 [235 185 207 ... 234 239 238]
 [251 191 124 ... 248 255 248]
 ...
 [180 236 247 ... 150 214 252]
 [114 232 255 ... 209 154 225]
 [127 249 247 ... 245 239  77]]
[[150 236 255 ... 246 151 149]
 [241 153 245 ... 255 246 241]
 [255 250 152 ... 255 255 255]
 ...
 [253 255 255 ... 173 231 255]
 [143 238 255 ... 255 160 235]
 [150 250 255 ... 255 241 155]]
[[148 245 255 ... 249 255 255]
 [246 161

[[152 152 176 ...  54  67 189]
 [150  64 136 ... 240 187 176]
 [180 140  96 ... 160 158 105]
 ...
 [ 57 245 165 ...  35 136  79]
 [ 60 189 145 ... 133  97 148]
 [190 182 112 ...  98 134  70]]
[[181 198 175 ... 112 149 100]
 [200  78 153 ... 155 181 255]
 [165 170  96 ... 160 172 122]
 ...
 [121 163 166 ... 105 137 117]
 [133 176 179 ... 120 153 147]
 [108 255 117 ... 125 150   5]]
[[136 171 199 ... 105  59  70]
 [161  78 125 ... 208 154  59]
 [213 109 100 ... 116 158 233]
 ...
 [108 202 108 ...  41 159 208]
 [ 48 156 165 ... 158 113 177]
 [ 77  57 235 ... 207 182  68]]
[[114 159 212 ... 133  45  51]
 [157 190 150 ... 180 120 138]
 [213 142 189 ... 161 212 236]
 ...
 [147 170 160 ...  41 138 147]
 [ 45 120 229 ... 144 183 182]
 [ 43 139 234 ... 141 180 157]]
[[111 204 238 ...  86 106  48]
 [206 174 182 ... 130 188 195]
 [247 166  47 ... 109 129 148]
 ...
 [ 92 124 112 ... 176 177 231]
 [100 185 144 ... 174  21 168]
 [ 55 182 153 ... 224 165 107]]
[[180 137 187 ...  55 147 134]
 [160   0

[[138 141 244 ... 175 146 114]
 [145 119 163 ... 234 185 215]
 [248 146 106 ... 249 223 227]
 ...
 [169 246 250 ... 138 151 175]
 [147 188 211 ... 149 168 184]
 [118 205 236 ... 179 182 127]]
[[160 254 241 ... 110 190 161]
 [253 141 234 ... 240 236 215]
 [243 227 129 ... 216 171 177]
 ...
 [121 235 206 ... 181 212 216]
 [180 235 175 ... 205 162 227]
 [165 217 179 ... 224 221 182]]
[[177 212 253 ... 146 172 155]
 [200 201 194 ... 187 188 191]
 [255 167  83 ... 167 204 242]
 ...
 [147 179 179 ... 128 242 206]
 [173 178 208 ... 234 171 182]
 [152 200 245 ... 210 180 136]]
[[148 226 241 ... 158 203 162]
 [220 176 136 ... 215 249 234]
 [228 154 146 ... 254 202 192]
 ...
 [165 208 255 ... 152 239 253]
 [198 240 200 ... 230 152 177]
 [163 232 199 ... 255 170 140]]
[[170 249 250 ... 243 189 157]
 [245 177 255 ... 255 248 241]
 [255 253 180 ... 243 239 245]
 ...
 [244 255 242 ... 180 241 255]
 [189 247 238 ... 243 182 243]
 [157 239 242 ... 255 243 175]]
[[171 250 255 ... 252 197 178]
 [248 188

In [ ]:
#read the labels
npdf = pd.read_csv('metadata/GC_features.csv')
source = npdf.label

In [ ]:
#normalise images array between 0 and 1
X = images2.astype('float32')
X /= 255
y = source

In [5]:
tf_callbacks = [
    tf.keras.callbacks.CSVLogger("TSPimagesTraining.csv", separator=",", append=False),
    tf.keras.callbacks.TensorBoard(log_dir='./logs',profile_batch = 100000000),
]

# Autkeras Model

In [ ]:
# Test Autokeras Model
clf = ak.ImageClassifier(overwrite=False, max_trials=1)
# Supervised training of the model
clf.fit(X, y, epochs=2, callbacks=tf_callbacks)

In [7]:
#export the selected model to check network architecture
model = clf.export_model()
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 32, 32)]          0         
_________________________________________________________________
cast_to_float32 (CastToFloat (None, 32, 32)            0         
_________________________________________________________________
expand_last_dim (ExpandLastD (None, 32, 32, 1)         0         
_________________________________________________________________
normalization (Normalization (None, 32, 32, 1)         3         
_________________________________________________________________
conv2d (Conv2D)              (None, 30, 30, 32)        320       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 28, 28, 64)        18496     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 64)        0     

In [ ]:
cv = KFold(n_splits=10, random_state=1, shuffle=True)
all_tests = []
all_predictions = []

for train_index, test_index in cv.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    clf = ak.ImageClassifier(overwrite= False, max_trials=1)

  # Supervised training of the model
    print("Start training")
    clf.fit(X_train, y_train, epochs=100, callbacks=tf_callbacks)

    print("Prendictions on unseen data")
    predicted_y = clf.predict(X_test)
    all_tests.append(y_test)
    all_predictions.append(predicted_y)
  #print(predicted_y)

In [37]:
predictions = []
for sublist in all_predictions:
    for item in sublist:
        predictions.append(int(item[0]))

tests = []
for sublist in all_tests:
    for item in sublist:
        tests.append(item)

In [38]:
report = classification_report(tests, predictions)
print(report)

              precision    recall  f1-score   support

           0       0.93      0.78      0.85      2500
           1       0.81      0.94      0.87      2500

    accuracy                           0.86      5000
   macro avg       0.87      0.86      0.86      5000
weighted avg       0.87      0.86      0.86      5000



In [39]:
from sklearn import metrics
from sklearn.metrics import accuracy_score,recall_score,precision_score
from sklearn.metrics import f1_score

print("Accuracy:",metrics.accuracy_score(tests, predictions))
precision = precision_score(tests, predictions)
recall = recall_score(tests, predictions)
f1_score = f1_score(tests, predictions)
print('Precision: %.3f' % precision)
print('Recall: %.3f' % recall)
print('F1-score: %.3f' % f1_score)

Accuracy: 0.86
Precision: 0.808
Recall: 0.944
F1-score: 0.871
