In [1]:
import os
import io
import random
import numpy as np
import pandas as pd
import networkx as nx
from PIL import Image
import autokeras as ak
import tensorflow as tf
from numpy import asarray
from tensorflow import keras
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from tensorflow.keras.callbacks import CSVLogger
from sklearn.datasets import load_files
from sklearn.metrics import classification_report
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold

In [2]:
def extractGCSynthicparams(file_path):
    instance = []
    lines = []
  #problem data start at line 5
    start = 0
    with open(file_path) as f:
        lines = f.read().splitlines()
        for i in range(start, len(lines)-1):
            line = lines[i].split(",")
            instance.append([int(line[0]),int(line[1])])
    #print(instance)
    return instance

In [3]:
import os
rootdir = 'All-6Set/DSATUR'
GCinstances = []
GClabels = []

for dir,subdir, files in os.walk(rootdir):
    for file in files:
        file_path = os.path.join(rootdir, file)
        instanceName = file[:-4]
        GCinstance = (instanceName, extractGCSynthicparams(file_path))
        if GCinstance[1] != []:        
            GCinstances.append(GCinstance)
            GClabels.append(1)
        else:
            print(instanceName + " has no edges!")

In [5]:
instancesGC = []
instancesGCNX = []
counter = 0
for instance in GCinstances:
    tempG = nx.Graph(name = instance[0])
    for count, vals in enumerate(instance[1]):    
        tempG.add_edge(vals[0], vals[1]) #create a graph of each instance
    instancesGCNX.append(tempG)
print(len(instancesGCNX))

2500


In [23]:
for i in instancesGCNX:
    marray = nx.convert_matrix.to_numpy_array(i)
    #multiply by 225 to convert to image
    for x in range(0, marray.shape[0]):
        for y in range(0, marray.shape[1]):
            if(marray[x,y] == 0):
                marray[x,y]+=255
            else:
                marray[x,y]-=1
        
    print(marray)
    im = Image.fromarray(marray)
    print(im.size)
    resized_image = im.resize((64, 64), Image.ANTIALIAS)
    new_p = resized_image.convert("L")
    new_p.save('gg/' + i.name + ".jpg")

[[255.   0.   0.   0. 255. 255. 255. 255. 255. 255.]
 [  0. 255.   0. 255.   0.   0.   0. 255. 255. 255.]
 [  0.   0. 255. 255. 255. 255. 255. 255.   0. 255.]
 [  0. 255. 255. 255.   0. 255.   0. 255.   0. 255.]
 [255.   0. 255.   0. 255. 255.   0.   0.   0. 255.]
 [255.   0. 255. 255. 255. 255.   0.   0. 255.   0.]
 [255.   0. 255.   0.   0.   0. 255. 255. 255. 255.]
 [255. 255. 255. 255.   0.   0. 255. 255. 255. 255.]
 [255. 255.   0.   0.   0. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255.   0. 255. 255. 255. 255.]]
(10, 10)
[[255.   0.   0.   0.   0.   0. 255. 255. 255. 255.]
 [  0. 255. 255. 255. 255.   0. 255.   0. 255. 255.]
 [  0. 255. 255.   0. 255. 255. 255.   0. 255. 255.]
 [  0. 255.   0. 255.   0. 255. 255. 255. 255.   0.]
 [  0. 255. 255.   0. 255. 255. 255. 255.   0. 255.]
 [  0.   0. 255. 255. 255. 255. 255. 255.   0.   0.]
 [255. 255. 255. 255. 255. 255. 255.   0.   0. 255.]
 [255.   0.   0. 255. 255. 255.   0. 255.   0.   0.]
 [255. 255. 255. 255.   0.   0.   0.

(102, 102)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ... 255.   0. 255.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255. 255.   0. ...   0. 255.   0.]
 [255.   0. 255. ... 255.   0. 255.]]
(102, 102)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0.   0.]
 [  0. 255. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(102, 102)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(102, 102)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(102, 102)
[[255.   0.   0. ... 255. 255. 25

(105, 105)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(105, 105)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(105, 105)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(105, 105)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(105, 105)
[[255.   0.   0. ... 255. 255. 25

(108, 108)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(108, 108)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255.   0. 255. ... 255. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(108, 108)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(108, 108)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(109, 109)
[[255.   0.   0. ... 255. 255. 25

(111, 111)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255. 255.]
 [255.   0.   0. ...   0. 255. 255.]]
(111, 111)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ...   0.   0. 255.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(111, 111)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(111, 111)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(111, 111)
[[255.   0.   0. ... 255. 255. 25

(114, 114)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255. 255.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ...   0. 255. 255.]]
(114, 114)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255. 255. 255. ...   0. 255. 255.]
 [255. 255. 255. ...   0. 255. 255.]]
(114, 114)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(114, 114)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255.   0.]
 [255. 255. 255. ...   0.   0. 255.]]
(114, 114)
[[255.   0.   0. ... 255. 255. 25

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(116, 116)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255.   0. 255. ... 255. 255. 255.]
 [255.   0.   0. ...   0. 255. 255.]]
(116, 116)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255. 255.   0. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(116, 116)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(114, 114)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

(118, 118)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255.   0.]
 [  0.   0. 255. ... 255.   0. 255.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255. 255.   0. ...   0. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]]
(118, 118)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255.   0.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255. 255.   0. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(118, 118)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 [  0. 255. 255. ... 255.   0. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]]
(118, 118)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 [  0. 255. 255. ... 255.   0. 255.]
 ...
 [255. 255. 255. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255.   0.]
 [255.   0. 255. ...   0.   0. 255.]]
(118, 118)
[[255.   0.   0. ... 255. 255. 25

(120, 120)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255. 255.]
 [255. 255.   0. ...   0. 255. 255.]]
(120, 120)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255. 255.]
 [255.   0.   0. ...   0. 255. 255.]]
(120, 120)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(120, 120)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(120, 120)
[[255.   0.   0. ... 255. 255. 25

(122, 122)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0.   0.]
 [  0. 255. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(122, 122)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255. 255.]
 [255.   0.   0. ...   0. 255. 255.]]
(122, 122)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(122, 122)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(122, 122)
[[255.   0.   0. ...   0. 255. 25

(125, 125)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(125, 125)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 [  0. 255. 255. ...   0. 255.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255. 255. 255. ...   0. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(125, 125)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(125, 125)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ... 255. 255.   0.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(125, 125)
[[255.   0.   0. ... 255. 255. 25

(128, 128)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(128, 128)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(128, 128)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255. 255.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255.   0. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(128, 128)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0. 255.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255.   0. 255. ...   0. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(128, 128)
[[255.   0.   0. ... 255. 255. 25

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(130, 130)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ... 255.   0.   0.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(130, 130)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(130, 130)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(130, 130)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(131, 131)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(131, 131)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(132, 132)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255. 255.]
 [  0.   0. 255. ... 255. 255.   0.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(132, 132)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 ...
 [255.   0. 255. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255. 255. 255. ...   0.   0. 255.]]
(134, 134)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255. 255.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255. 255.   0. ... 255.   0. 255.]
 [255. 255.   0. ...   0. 255.   0.]
 [255. 255. 255. ... 255.   0. 255.]]
(134, 134)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255. 255. 255.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(134, 134)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0.   0.]
 [  0. 255. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(134, 134)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255.   0.   0. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(136, 136)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255. 255.]
 [  0.   0. 255. ...   0. 255. 255.]
 ...
 [255. 255.   0. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255.   0. 255.]]
(136, 136)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255.   0. 255.]
 [255. 255.   0. ...   0. 255.   0.]
 [255.   0. 255. ... 255.   0. 255.]]
(136, 136)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255.   0.   0. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(136, 136)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

(139, 139)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255.   0. 255. ...   0. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(139, 139)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(139, 139)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]]
(139, 139)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 ...
 [255. 255. 255. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255. 255.]
 [255. 255. 255. ...   0. 255. 255.]]
(139, 139)
[[255.   0.   0. ... 255. 255. 25

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 [  0. 255. 255. ... 255.   0.   0.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(140, 140)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ... 255.   0.   0.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(140, 140)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255.   0. 255.]
 [255. 255.   0. ...   0. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(140, 140)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(140, 140)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

(143, 143)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255.   0.]
 [255.   0. 255. ... 255.   0. 255.]]
(143, 143)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0. 255.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255. 255.   0. ... 255. 255.   0.]
 [255.   0. 255. ... 255. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(143, 143)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255. 255.]
 [255. 255.   0. ...   0. 255. 255.]]
(143, 143)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255.   0. ... 255. 255. 255.]
 [255. 255.   0. ...   0. 255. 255.]]
(143, 143)
[[255.   0.   0. ... 255. 255. 25

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 [  0. 255. 255. ...   0.   0. 255.]
 ...
 [255. 255.   0. ... 255. 255. 255.]
 [255.   0.   0. ... 255. 255.   0.]
 [255. 255. 255. ... 255.   0. 255.]]
(145, 145)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 ...
 [255. 255. 255. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255. 255.]
 [255. 255. 255. ...   0. 255. 255.]]
(145, 145)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(145, 145)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255.   0.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255. 255.   0. ... 255. 255.   0.]
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0.   0. ...   0. 255. 255.]]
(145, 145)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(145, 145)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255. 255.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255. 255.   0. ... 255. 255.   0.]
 [255. 255.   0. ... 255. 255. 255.]
 [255. 255. 255. ...   0. 255. 255.]]
(148, 148)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255.   0.   0.]
 [255. 255. 255. ...   0. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(148, 148)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255.   0. 255. ...   0. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(148, 148)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(150, 150)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(150, 150)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255.   0. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(150, 150)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 [  0. 255. 255. ... 255.   0. 255.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255.   0. ... 255. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(150, 150)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

(152, 152)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 ...
 [255. 255.   0. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(152, 152)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255.   0.]
 [255. 255.   0. ... 255.   0. 255.]]
(152, 152)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255. 255.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255.   0. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(152, 152)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(152, 152)
[[255.   0.   0. ... 255. 255. 25

(154, 154)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(154, 154)
[[255.   0.   0. ...   0.   0.   0.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... 255.   0.   0.]
 [  0.   0.   0. ...   0. 255.   0.]
 [  0.   0.   0. ...   0.   0. 255.]]
(154, 154)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0. 255.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255. 255.   0. ... 255.   0. 255.]
 [255.   0. 255. ...   0. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(154, 154)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255.   0.]
 [  0. 255. 255. ... 255.   0. 255.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(154, 154)
[[255.   0.   0. ... 255. 255. 25

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255. 255. 255. ...   0.   0. 255.]]
(157, 157)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ...   0. 255. 255.]
 ...
 [255. 255.   0. ... 255.   0. 255.]
 [255.   0. 255. ...   0. 255.   0.]
 [255.   0. 255. ... 255.   0. 255.]]
(157, 157)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(157, 157)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0.   0.]
 [  0. 255. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(157, 157)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

(160, 160)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(160, 160)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(160, 160)
[[255.   0.   0. ...   0.   0.   0.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... 255.   0.   0.]
 [  0.   0.   0. ...   0. 255.   0.]
 [  0.   0.   0. ...   0.   0. 255.]]
(160, 160)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255. 255. ...   0.   0. 255.]]
(160, 160)
[[255.   0.   0. ... 255. 255. 25

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(163, 163)
[[255.   0.   0. ...   0. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(163, 163)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255. 255.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(163, 163)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(163, 163)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(165, 165)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(165, 165)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255.   0. 255.]]
(165, 165)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(164, 164)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

(167, 167)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]
 [255.   0.   0. ... 255. 255. 255.]]
(167, 167)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255.   0. 255.]
 ...
 [255.   0. 255. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0. 255. ...   0.   0. 255.]]
(167, 167)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255.   0. 255.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]]
(168, 168)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(168, 168)
[[255.   0.   0. ... 255. 255. 25

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(170, 170)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(170, 170)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0. 255.]
 [  0. 255. 255. ...   0. 255.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(170, 170)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255. 255.]
 [255.   0.   0. ...   0. 255. 255.]]
(170, 170)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

(171, 171)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0. 255.]
 [  0. 255. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255. 255. 255. ...   0.   0. 255.]]
(171, 171)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0. 255.]
 [  0. 255. 255. ...   0. 255.   0.]
 ...
 [255.   0.   0. ... 255.   0. 255.]
 [255.   0. 255. ...   0. 255.   0.]
 [255. 255.   0. ... 255.   0. 255.]]
(172, 172)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(172, 172)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(172, 172)
[[255.   0.   0. ... 255. 255. 25

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(174, 174)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(174, 174)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(174, 174)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0.   0.]
 [  0. 255. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(174, 174)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0. 255.]
 [  0.   0. 255. ...   0. 255. 255.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255. 255.]
 [255. 255. 255. ...   0. 255. 255.]]
(176, 176)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(176, 176)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255. 255.   0. ... 255. 255. 255.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0. 255. ... 255.   0. 255.]]
(176, 176)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(175, 175)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(178, 178)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ...   0. 255. 255.]]
(178, 178)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(178, 178)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0. 255.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255.   0. 255.]]
(178, 178)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0.   0.]
 [  0. 255. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255. 255.]
 [255.   0.   0. ...   0. 255. 255.]]
(180, 180)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(180, 180)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0. 255. ...   0.   0. 255.]]
(180, 180)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(180, 180)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(182, 182)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0.   0.]
 [  0. 255. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(182, 182)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(182, 182)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255.   0.]
 [255.   0. 255. ...   0.   0. 255.]]
(182, 182)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(184, 184)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(184, 184)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(184, 184)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(184, 184)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255.   0.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(186, 186)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(186, 186)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0. 255.]
 [255. 255.   0. ...   0. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(187, 187)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255.   0. 255.]
 [255. 255.   0. ...   0. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]]
(187, 187)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255. 255.]
 [  0.   0. 255. ... 255.   0. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255.   0.]
 [255. 255. 255. ... 255.   0. 255.]]
(188, 188)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255.   0.]
 [  0. 255. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(188, 188)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(188, 188)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255.   0.]
 [  0. 255. 255. ...   0. 255. 255.]
 ...
 [255.   0.   0. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]]
(189, 189)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255.   0.]
 [255.   0. 255. ... 255.   0. 255.]]
(190, 190)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255. 255.   0. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0. 255. ... 255.   0. 255.]]
(190, 190)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255.   0. 255.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0. 255. ...   0.   0. 255.]]
(190, 190)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255.   0.]
 [  0. 255. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(190, 190)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(192, 192)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255. 255. 255.]
 [255.   0.   0. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(192, 192)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255.   0.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(192, 192)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(191, 191)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255. 255. 255. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(194, 194)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0.   0.]
 [  0. 255. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(194, 194)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(194, 194)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(194, 194)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255.   0.   0. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255. 255.]
 [255.   0.   0. ... 255. 255. 255.]]
(196, 196)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(196, 196)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(193, 193)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 ...
 [255.   0.   0. ... 255.   0. 255.]
 [255.   0. 255. ...   0. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(196, 196)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 

(198, 198)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255. 255. 255.]
 [255.   0.   0. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(198, 198)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 [  0. 255. 255. ... 255.   0.   0.]
 ...
 [255. 255. 255. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(198, 198)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ... 255.   0. 255.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255. 255.]
 [255. 255. 255. ...   0. 255. 255.]]
(198, 198)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0.   0.]
 [  0. 255. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(198, 198)
[[255.   0.   0. ... 255. 255. 25

[[255.   0.   0.   0.   0.   0.   0. 255. 255. 255. 255. 255. 255. 255.
  255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [  0. 255. 255. 255.   0.   0. 255. 255. 255. 255.   0. 255. 255. 255.
  255. 255.   0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255. 255.   0. 255. 255.   0. 255. 255. 255. 255. 255. 255.   0.
  255.   0.   0. 255. 255. 255. 255.   0. 255. 255.]
 [  0. 255.   0. 255.   0.   0. 255. 255. 255.   0. 255. 255.   0.   0.
    0. 255.   0. 255.   0. 255. 255.   0. 255.   0.]
 [  0.   0. 255.   0. 255. 255.   0.   0. 255.   0. 255. 255. 255. 255.
  255.   0. 255.   0. 255.   0. 255. 255. 255. 255.]
 [  0.   0. 255.   0. 255. 255. 255. 255. 255. 255. 255.   0. 255.   0.
  255. 255. 255.   0. 255.   0. 255. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255. 255.   0. 255. 255. 255.   0. 255.   0.
  255. 255. 255. 255. 255. 255.   0. 255.   0. 255.]
 [255. 255. 255. 255.   0. 255.   0. 255.   0.   0.   0.   0.   0. 255.
  255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]


[[255.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0. 255. 255. 255. 255. 255. 255. 255.]
 [  0. 255. 255.   0. 255.   0.   0. 255.   0. 255.   0.   0.   0.   0.
  255.   0.   0. 255. 255.   0.   0. 255.   0. 255.   0.   0.   0.   0.]
 [  0. 255. 255.   0.   0.   0.   0. 255. 255.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 255.   0.   0.   0. 255. 255.   0.   0.]
 [  0.   0.   0. 255.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  255.   0.   0.   0.   0.   0.   0.   0.   0. 255.   0.   0. 255. 255.]
 [  0. 255.   0.   0. 255.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0. 255.   0.   0. 255.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 255. 255.   0. 255.   0.   0.   0.   0. 255.
  255. 255. 255. 255. 255. 255.   0.   0. 255. 255.   0.   0. 255. 255.]
 [  0.   0.   0.   0.   0. 255. 255.   0.   0.   0.   0.   0. 255. 255.
    0.   0. 255.   0.   0. 255.   0. 255.   0.   0.   0.  

[[255.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255.
  255. 255. 255.]
 [  0. 255. 255.   0.   0. 255.   0.   0. 255. 255.   0.   0. 255.   0.
  255. 255.   0. 255.   0.   0. 255. 255. 255. 255.   0. 255.   0.   0.
  255.   0.   0.]
 [  0. 255. 255.   0.   0. 255. 255.   0.   0.   0.   0.   0. 255.   0.
  255. 255.   0. 255.   0. 255.   0.   0. 255.   0. 255.   0. 255.   0.
  255.   0. 255.]
 [  0.   0.   0. 255.   0. 255.   0. 255.   0. 255.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0. 255. 255. 255. 255.   0. 255.   0. 255.
    0. 255. 255.]
 [  0.   0.   0.   0. 255. 255. 255. 255.   0.   0.   0.   0.   0. 255.
  255. 255.   0. 255. 255.   0.   0.   0.   0.   0.   0.   0. 255. 255.
  255. 255.   0.]
 [  0. 255. 255. 255. 255. 255.   0. 255. 255.   0. 255.   0.   0. 255.
    0. 255. 255. 255. 255.   0.   0. 255.   0.   0. 255. 255.   0.   0.
  255.   0. 255.]
 [  0.   0. 255.   0. 255.  

(33, 33)
[[255.   0.   0. ...   0.   0. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [  0. 255.   0. ... 255. 255.   0.]
 [  0.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(33, 33)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(33, 33)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255.   0.]
 [255. 255. 255. ... 255.   0. 255.]]
(33, 33)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255.   0.]
 [255. 255.   0. ... 255.   0. 255.]]
(34, 34)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ...   0. 255. 255.]]
(37, 37)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255.   0. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(37, 37)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255. 255.   0.]
 [255. 255.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(37, 37)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255.   0.]
 [255. 255.   0. ... 255.   0. 255.]]
(37, 37)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0

[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255.   0. 255. ...   0. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]]
(44, 44)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255.   0.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255.   0. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(44, 44)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255. 255.]
 [255. 255.   0. ...   0. 255. 255.]]
(44, 44)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0. 255.]
 [  0. 255. 255. ...   0. 255.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255. 255.]
 [255. 255.   0. ...   0. 255. 255.]]
(44, 44)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255

(49, 49)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255.   0. 255.]]
(45, 45)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(49, 49)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255. 255.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255. 255.]
 [255. 255. 255. ...   0. 255. 255.]]
(49, 49)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(48, 48)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(53, 53)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255.   0.]
 [  0. 255. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255. 255.   0.]
 [255. 255.   0. ... 255. 255.   0.]
 [255.   0. 255. ...   0.   0. 255.]]
(53, 53)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(54, 54)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(54, 54)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(54, 54)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(56, 56)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255.   0. 255. ...   0. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(56, 56)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255.   0. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255.   0. 255.]]
(56, 56)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255.   0.]
 [  0.   0. 255. ... 255. 255.   0.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0.   0. ... 255. 255. 255.]]
(56, 56)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255.   0.]
 [  0. 255. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255. 255.   0.]
 [255. 255.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(56, 56)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(58, 58)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(59, 59)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(59, 59)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255.   0.]
 [255. 255.   0. ... 255.   0. 255.]]
(59, 59)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(59, 59)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(62, 62)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0.   0.]
 [  0. 255. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(62, 62)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0. 255.]
 ...
 [255. 255.   0. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255.   0.]
 [255. 255. 255. ... 255.   0. 255.]]
(62, 62)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(62, 62)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(62, 62)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(66, 66)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255. 255.   0.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(66, 66)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ...   0. 255. 255.]]
(66, 66)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(66, 66)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(66, 66)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

 [255.   0.   0. ...   0. 255. 255.]]
(68, 68)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255.   0. 255. ...   0. 255. 255.]
 [255.   0.   0. ... 255. 255. 255.]]
(68, 68)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(69, 69)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(69, 69)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255.   0.]
 [  0.   0. 255. ...   0. 255.   0.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255. 255. 255. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(69, 69)
[[255

(71, 71)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255.   0.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255.   0. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(71, 71)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255.   0.]
 [255. 255. 255. ... 255.   0. 255.]]
(71, 71)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 ...
 [255. 255.   0. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(72, 72)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ...   0. 255.   0.]
 ...
 [255. 255.   0. ... 255. 255.   0.]
 [255.   0. 255. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(72, 72)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(75, 75)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(75, 75)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255. 255.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(75, 75)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(75, 75)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]]
(75, 75)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(78, 78)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255. 255.   0.]
 [  0.   0. 255. ... 255.   0.   0.]
 ...
 [255. 255. 255. ... 255.   0. 255.]
 [255. 255.   0. ...   0. 255. 255.]
 [255.   0.   0. ... 255. 255. 255.]]
(78, 78)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255.   0. 255.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0. 255. ...   0.   0. 255.]]
(78, 78)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0. 255. ...   0.   0. 255.]]
(78, 78)
[[255.   0.   0. ...   0.   0. 255.]
 [  0. 255.   0. ... 255.   0. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0.   0. ...   0. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(78, 78)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(80, 80)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255. 255. 255.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0. 255. ... 255.   0. 255.]]
(81, 81)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(80, 80)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255. 255.]
 [255.   0.   0. ...   0. 255. 255.]]
(81, 81)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(81, 81)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(84, 84)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0. 255. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255. 255.   0. ...   0. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(84, 84)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255. 255.   0. ...   0.   0. 255.]]
(84, 84)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 ...
 [255. 255.   0. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(84, 84)
[[255.   0.   0. ...   0. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255. 255.]
 [255.   0.   0. ...   0. 255. 255.]]
(84, 84)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(87, 87)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ... 255.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255. 255.   0. ... 255.   0. 255.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ... 255.   0. 255.]]
(87, 87)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255. 255. 255. ...   0.   0. 255.]]
(87, 87)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0.   0.   0.]
 [  0. 255. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ... 255. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(87, 87)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255.   0.   0.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(87, 87)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(89, 89)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 ...
 [255.   0.   0. ... 255. 255.   0.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ...   0. 255. 255.]]
(89, 89)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 [  0. 255. 255. ... 255.   0. 255.]
 ...
 [255.   0. 255. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255.   0.]
 [255. 255. 255. ... 255.   0. 255.]]
(90, 90)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255.   0.]
 [  0. 255. 255. ... 255.   0. 255.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255. 255.   0. ...   0. 255. 255.]
 [255.   0. 255. ... 255. 255. 255.]]
(90, 90)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ...   0. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255.   0. 255. ... 255.   0. 255.]
 [255. 255. 255. ...   0. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(90, 90)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(93, 93)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(93, 93)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255.   0. ... 255. 255. 255.]]
(93, 93)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 [  0. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
(93, 93)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255. 255. ... 255.   0.   0.]
 [  0. 255. 255. ... 255. 255.   0.]
 ...
 [255. 255. 255. ... 255. 255.   0.]
 [255.   0. 255. ... 255. 255. 255.]
 [255.   0.   0. ...   0. 255. 255.]]
(94, 94)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.

(97, 97)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0. 255.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255. 255.]
 [255.   0. 255. ...   0. 255. 255.]]
(97, 97)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0. 255.]
 [  0.   0. 255. ... 255. 255. 255.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255.   0.]
 [255. 255. 255. ...   0.   0. 255.]]
(97, 97)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ...   0.   0.   0.]
 ...
 [255.   0.   0. ... 255.   0.   0.]
 [255.   0.   0. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(97, 97)
[[255.   0.   0. ... 255. 255. 255.]
 [  0. 255.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255. 255.   0.]
 ...
 [255.   0. 255. ... 255.   0.   0.]
 [255.   0. 255. ...   0. 255.   0.]
 [255.   0.   0. ...   0.   0. 255.]]
(97, 97)
[[255.   0.   0. ... 255. 255. 255.]
 [  0.